<?php

namespace Database\Seeders;

use App\Models\Shop;
use App\Models\Vendor;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class ShopSeeder extends Seeder
{
    public function run(): void
    {
        $vendors = Vendor::query()->get();

        if ($vendors->isEmpty()) {
            $vendors = Vendor::factory()->count(3)->create();
        }

        foreach ($vendors as $vendor) {
            $name = $vendor->name ? "{$vendor->name} Shop" : 'Demo Shop';
            $slug = Str::slug($vendor->name ?? 'demo-shop') . '-' . $vendor->id;

            Shop::firstOrCreate(
                ['vendor_id' => $vendor->id, 'slug' => $slug],
                [
                    'name' => $name,
                    'logo' => null,
                    'description' => 'Demo shop generated by seeder.',
                    'status' => 'active',
                ]
            );
        }
    }
}
